using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.SqlServer.Server;

public partial class CoreContent
{
    // 量词正则串
    public static string QUANTIFIER_NAME = "";

    public static void ReloadQuantifierName()
    {
        // 记录日志
        Log.LogMessage("CoreContent", "ReloadQuantifierName", "加载量词！");
        // 设置正则串
        QUANTIFIER_NAME = ReloadStringValue("实词", "量词");
        // 记录日志
        Log.LogMessage(QUANTIFIER_NAME);
    }

    public static void AddQuantifierName(string name)
    {
        // 指令字符串
        string cmdString = "INSERT INTO [dbo].[CoreContent] " +
            "([classification], [content], [attribute]) " +
            "VALUES ('实词', @SqlContent, '量词'); ";
        // 设置参数
        Dictionary<string, string> parameters = new Dictionary<string, string>();
        // 加入参数
        parameters.Add("SqlContent", name);
        // 执行指令
        NLDB.ExecuteNonQuery(cmdString, parameters);
    }

    public static void AddAllQuantifierNames()
    {
        // 记录日志
        Log.LogMessage("CoreContent", "AddAllQuantifierNames", "加载量词！");

        AddQuantifierName("把");
        AddQuantifierName("班");
        AddQuantifierName("般");
        AddQuantifierName("板");
        AddQuantifierName("版");
        AddQuantifierName("瓣");
        AddQuantifierName("帮");
        AddQuantifierName("包");
        AddQuantifierName("抱");
        AddQuantifierName("杯");
        AddQuantifierName("辈");
        AddQuantifierName("辈子");
        AddQuantifierName("本");
        AddQuantifierName("笔");
        AddQuantifierName("边");
        AddQuantifierName("彪");
        AddQuantifierName("柄");
        AddQuantifierName("拨");
        AddQuantifierName("钵");
        AddQuantifierName("簸箕");
        AddQuantifierName("部");
        AddQuantifierName("部分");
        AddQuantifierName("步");
        AddQuantifierName("餐");
        AddQuantifierName("册");
        AddQuantifierName("层");
        AddQuantifierName("茬");
        AddQuantifierName("场");
        AddQuantifierName("车");
        AddQuantifierName("车皮");
        AddQuantifierName("匙");
        AddQuantifierName("池");
        AddQuantifierName("出");
        AddQuantifierName("处");
        AddQuantifierName("船");
        AddQuantifierName("串");
        AddQuantifierName("床");
        AddQuantifierName("丛");
        AddQuantifierName("簇");
        AddQuantifierName("沓");
        AddQuantifierName("代");
        AddQuantifierName("袋");
        AddQuantifierName("担");
        AddQuantifierName("刀");
        AddQuantifierName("道");
        AddQuantifierName("等");
        AddQuantifierName("滴");
        AddQuantifierName("点");
        AddQuantifierName("碟");
        AddQuantifierName("叠");
        AddQuantifierName("顶");
        AddQuantifierName("锭");
        AddQuantifierName("栋");
        AddQuantifierName("兜");
        AddQuantifierName("蔸");
        AddQuantifierName("堵");
        AddQuantifierName("段");
        AddQuantifierName("堆");
        AddQuantifierName("对");
        AddQuantifierName("队");
        AddQuantifierName("墩");
        AddQuantifierName("囤");
        AddQuantifierName("朵");
        AddQuantifierName("垛");
        AddQuantifierName("驮");
        AddQuantifierName("发");
        AddQuantifierName("番");
        AddQuantifierName("方");
        AddQuantifierName("房");
        AddQuantifierName("分");
        AddQuantifierName("份");
        AddQuantifierName("封");
        AddQuantifierName("峰");
        AddQuantifierName("幅");
        AddQuantifierName("副");
        AddQuantifierName("服");
        AddQuantifierName("竿");
        AddQuantifierName("杆");
        AddQuantifierName("缸");
        AddQuantifierName("格");
        AddQuantifierName("根");
        AddQuantifierName("钩");
        AddQuantifierName("股");
        AddQuantifierName("挂");
        AddQuantifierName("管");
        AddQuantifierName("罐");
        AddQuantifierName("贯");
        AddQuantifierName("桄");
        AddQuantifierName("锅");
        AddQuantifierName("行");
        AddQuantifierName("号");
        AddQuantifierName("盒");
        AddQuantifierName("痕");
        AddQuantifierName("泓");
        AddQuantifierName("壶");
        AddQuantifierName("户");
        AddQuantifierName("环");
        AddQuantifierName("伙");
        AddQuantifierName("辑");
        AddQuantifierName("集");
        AddQuantifierName("级");
        AddQuantifierName("剂");
        AddQuantifierName("季");
        AddQuantifierName("家");
        AddQuantifierName("夹");
        AddQuantifierName("架");
        AddQuantifierName("驾");
        AddQuantifierName("间");
        AddQuantifierName("肩");
        AddQuantifierName("件");
        AddQuantifierName("角");
        AddQuantifierName("窖");
        AddQuantifierName("截");
        AddQuantifierName("节");
        AddQuantifierName("介");
        AddQuantifierName("届");
        AddQuantifierName("进");
        AddQuantifierName("茎");
        AddQuantifierName("局");
        AddQuantifierName("具");
        AddQuantifierName("句");
        AddQuantifierName("卷");
        AddQuantifierName("开");
        AddQuantifierName("窠");
        AddQuantifierName("棵");
        AddQuantifierName("颗");
        AddQuantifierName("孔");
        AddQuantifierName("口");
        AddQuantifierName("块");
        AddQuantifierName("筐");
        AddQuantifierName("捆");
        AddQuantifierName("栏");
        AddQuantifierName("篮");
        AddQuantifierName("揽子");
        AddQuantifierName("粒");
        AddQuantifierName("例");
        AddQuantifierName("辆");
        AddQuantifierName("列");
        AddQuantifierName("领");
        AddQuantifierName("流");
        AddQuantifierName("绺");
        AddQuantifierName("溜");
        AddQuantifierName("笼");
        AddQuantifierName("垄");
        AddQuantifierName("篓");
        AddQuantifierName("炉");
        AddQuantifierName("路");
        AddQuantifierName("缕");
        AddQuantifierName("轮");
        AddQuantifierName("箩");
        AddQuantifierName("摞");
        AddQuantifierName("码");
        AddQuantifierName("脉");
        AddQuantifierName("毛");
        AddQuantifierName("枚");
        AddQuantifierName("门");
        AddQuantifierName("面");
        AddQuantifierName("名");
        AddQuantifierName("抹");
        AddQuantifierName("幕");
        AddQuantifierName("年");
        AddQuantifierName("排");
        AddQuantifierName("派");
        AddQuantifierName("盘");
        AddQuantifierName("泡");
        AddQuantifierName("盆");
        AddQuantifierName("棚");
        AddQuantifierName("捧");
        AddQuantifierName("批");
        AddQuantifierName("匹");
        AddQuantifierName("篇");
        AddQuantifierName("片");
        AddQuantifierName("瓢");
        AddQuantifierName("撇");
        AddQuantifierName("瓶");
        AddQuantifierName("期");
        AddQuantifierName("畦");
        AddQuantifierName("起");
        AddQuantifierName("腔");
        AddQuantifierName("墙");
        AddQuantifierName("锹");
        AddQuantifierName("丘");
        AddQuantifierName("曲");
        AddQuantifierName("阕");
        AddQuantifierName("群");
        AddQuantifierName("任");
        AddQuantifierName("色");
        AddQuantifierName("扇");
        AddQuantifierName("勺");
        AddQuantifierName("哨");
        AddQuantifierName("身");
        AddQuantifierName("声");
        AddQuantifierName("乘");
        AddQuantifierName("首");
        AddQuantifierName("手");
        AddQuantifierName("树");
        AddQuantifierName("束");
        AddQuantifierName("双");
        AddQuantifierName("丝");
        AddQuantifierName("艘");
        AddQuantifierName("所");
        AddQuantifierName("台");
        AddQuantifierName("抬");
        AddQuantifierName("滩");
        AddQuantifierName("摊");
        AddQuantifierName("坛");
        AddQuantifierName("潭");
        AddQuantifierName("塘");
        AddQuantifierName("堂");
        AddQuantifierName("樘");
        AddQuantifierName("套");
        AddQuantifierName("提");
        AddQuantifierName("屉");
        AddQuantifierName("挑");
        AddQuantifierName("条");
        AddQuantifierName("贴");
        AddQuantifierName("帖");
        AddQuantifierName("听");
        AddQuantifierName("挺");
        AddQuantifierName("通");
        AddQuantifierName("筒");
        AddQuantifierName("头");
        AddQuantifierName("团");
        AddQuantifierName("坨");
        AddQuantifierName("弯");
        AddQuantifierName("丸");
        AddQuantifierName("汪");
        AddQuantifierName("网");
        AddQuantifierName("尾");
        AddQuantifierName("味");
        AddQuantifierName("位");
        AddQuantifierName("瓮");
        AddQuantifierName("窝");
        AddQuantifierName("握");
        AddQuantifierName("席");
        AddQuantifierName("袭");
        AddQuantifierName("匣");
        AddQuantifierName("线");
        AddQuantifierName("箱");
        AddQuantifierName("项");
        AddQuantifierName("些");
        AddQuantifierName("宿");
        AddQuantifierName("眼");
        AddQuantifierName("页");
        AddQuantifierName("叶");
        AddQuantifierName("印张");
        AddQuantifierName("羽");
        AddQuantifierName("园");
        AddQuantifierName("员");
        AddQuantifierName("扎");
        AddQuantifierName("则");
        AddQuantifierName("盏");
        AddQuantifierName("章");
        AddQuantifierName("张");
        AddQuantifierName("着");
        AddQuantifierName("折");
        AddQuantifierName("针");
        AddQuantifierName("帧");
        AddQuantifierName("支");
        AddQuantifierName("枝");
        AddQuantifierName("纸");
        AddQuantifierName("指");
        AddQuantifierName("盅");
        AddQuantifierName("轴");
        AddQuantifierName("株");
        AddQuantifierName("注");
        AddQuantifierName("炷");
        AddQuantifierName("柱");
        AddQuantifierName("桩");
        AddQuantifierName("幢");
        AddQuantifierName("桌");
        AddQuantifierName("宗");
        AddQuantifierName("组");
        AddQuantifierName("嘴");
        AddQuantifierName("尊");
        AddQuantifierName("樽");
        AddQuantifierName("撮");
        AddQuantifierName("座");
        AddQuantifierName("平");
        AddQuantifierName("次");
        AddQuantifierName("重");
        AddQuantifierName("居");
        AddQuantifierName("个");
        AddQuantifierName("只");
        AddQuantifierName("岁");
        AddQuantifierName("种");

        // 记录日志
        Log.LogMessage("CoreContent", "AddAllQuantifierNames", "量词已加载！");
    }
}
